name: Check Steam Free Weekends

on:
  schedule:
    - cron: "0 0/12 * * *" # Runs every 12 hours.

jobs:
  check_free_weekends:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run script to check for Free Weekends
      env:
        STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      run: python check_free_weekends.py

    - name: Commit README.md
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add README.md
        git commit -m "Update README.md"
        git push
