name: Check Steam Free Weekends

on:
  schedule:
    - cron: "0 0/12 * * *" # Runs every 12 hours.

jobs:
  check_free_weekends:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run script to check for Free Weekends
      env:
        STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      run: python check_free_weekends.py

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

    - name: Commit README.md
      run: |
        git add README.md
        git commit -m "Update README.md"

    - name: Push changes
      if: github.ref == 'refs/heads/main'  # Only push changes if the trigger is on the main branch
      run: |
        git push origin HEAD:main --force

    - name: Clear commit
      run: |
        git checkout --orphan tmp
        git commit -m "$(date)"
        git branch -D main
        git branch -m tmp main
        git push --set-upstream origin main -f
